/**
 * Created by Carlyeah on 5/23/15.
 */
var coffee, config, exec, gulp, gutil, rename;

gulp = require('gulp');

gutil = require('gulp-util');

coffee = require('gulp-coffee');

exec = require('gulp-exec');

rename = require('gulp-rename');

config = {
    watchers: {
        index: '*.coffee',
        files: 'App/**/*.coffee'
    },
    index: {
        src: 'index.ios.coffee',
        dist: './'
    },
    files: {
        src: 'App/**/*.coffee',
        dist: './App/dist'
    }
};

gulp.task('build', function() {
    var options;
    options = {
        continueOnError: false,
        pipeStdout: true
    };
    gulp.src(config.files.src).pipe(exec('cjsx-transform <%= file.path %>', options)).pipe(rename(function(path) {
        path.extname = '.js';
    })).pipe(coffee({
        bare: true
    }).on('error', gutil.log)).pipe(gulp.dest(config.files.dist));
});

gulp.task('cjsx', ['build'], function() {
    var options;
    options = {
        continueOnError: false,
        pipeStdout: true
    };
    gulp.src(config.index.src).pipe(exec('cjsx-transform <%= file.path %>', options)).pipe(coffee({
        bare: true
    }).on('error', gutil.log)).pipe(gulp.dest(config.index.dist));
});

gulp.task('watch', ['cjsx'], function() {
    gulp.watch([config.watchers.index, config.watchers.files], ['cjsx']);
});

gulp.task('default', ['watch']);

// ---
// generated by coffee-script 1.9.2